# Generated by Django 5.1.2 on 2024-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du cours (ex. Mathématiques)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du cours')),
                ('niveau', models.CharField(help_text='Niveau du cours (ex. Seconde, Première)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de famille de l'enseignant", max_length=50)),
                ('prenom', models.CharField(help_text="Prénom de l'enseignant", max_length=50)),
                ('date_de_naissance', models.DateField(help_text="Date de naissance de l'enseignant")),
                ('email', models.EmailField(help_text="Adresse email professionnelle de l'enseignant", max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, help_text="Numéro de téléphone de l'enseignant", max_length=15, null=True)),
                ('specialite', models.CharField(help_text="Spécialité de l'enseignant (ex. Mathématiques, Physique)", max_length=100)),
                ('diplome', models.CharField(help_text="Dernier diplôme obtenu par l'enseignant", max_length=100)),
                ('date_embauche', models.DateField(help_text="Date d'embauche de l'enseignant dans l'établissement")),
                ('statut', models.CharField(choices=[('titulaire', 'Titulaire'), ('vacataire', 'Vacataire')], default='titulaire', help_text="Statut de l'enseignant dans l'établissement", max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du dossier")),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification du dossier')),
                ('cours_enseignes', models.ManyToManyField(help_text="Cours enseignés par l'enseignant", related_name='enseignants', to='gestion_administratif.cours')),
            ],
        ),
    ]
