# Generated by Django 5.1.2 on 2024-10-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
