# Generated by Django 5.1.2 on 2024-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0004_enseignant_matricule_enseignant_ufr_module_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='is_vacataire',
            field=models.BooleanField(default=False, verbose_name='Est Vacataire'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro Matricule'),
        ),
    ]
